// <auto-generated />
using System;
using Buvette.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buvette.Data.Migrations
{
    [DbContext(typeof(BuvetteContext))]
    [Migration("20260918115309_ComptageDeCaisseEtGratuites")]
    partial class ComptageDeCaisseEtGratuites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Buvette.Data.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvenementId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Offerte")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("Buvette.Data.Evenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cloture")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FondDeCaisse")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontantCompte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("Buvette.Data.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ProduitId");

                    b.ToTable("Lignes");
                });

            modelBuilder.Entity("Buvette.Data.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvenementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockInitial")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Buvette.Data.Commande", b =>
                {
                    b.HasOne("Buvette.Data.Evenement", "Evenement")
                        .WithMany("Commandes")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("Buvette.Data.LigneCommande", b =>
                {
                    b.HasOne("Buvette.Data.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buvette.Data.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Buvette.Data.Produit", b =>
                {
                    b.HasOne("Buvette.Data.Evenement", "Evenement")
                        .WithMany("Produits")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("Buvette.Data.Commande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Buvette.Data.Evenement", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
